#!/bin/sh

# this is just a test script.  It was more important back before
# slowdown learned to accept command line arguments for the command to
# be managed.

if [ 1 = 1 ]
then
	for i in `seq 100`
	do
		echo $i
		ls -l
	done
else
	/bin/ls
fi
