uint8_t PL_save_config(void);
void PL_persistence_thread(void);


#define CONFIG_ATTR_STREAM 652
#define CONFIG_ATTR_RSS 344
#define CONFIG_ATTR_ALARM  525
#define CONFIG_ATTR_VOLUME 664
#define CONFIG_ATTR_SLEEP_TIMER 1177
#define CONFIG_ATTR_SNOOZE_TIMER 1310
#define CONFIG_ATTR_SAY_HOUR 1404
#define CONFIG_ATTR_TIMEZONE 875
#define CONFIG_ATTR_WIFI_SSID 961
#define CONFIG_ATTR_WIFI_PSK 1409
#define CONFIG_ATTR_WIFI_TYPE 976
#define CONFIG_ATTR_WIFI_DRIVER 1178
#define CONFIG_ATTR_USE_NTP 766
#define CONFIG_ATTR_NTP_SERVER 1096
#define CONFIG_ATTR_SSH_ACCESS 1055
#define CONFIG_ATTR_WWW_ACCESS 1078
#define CONFIG_ATTR_IP_ADDR 1054
#define CONFIG_ATTR_IP_MASK 1067
#define CONFIG_ATTR_IP_GW 1066
#define CONFIG_ATTR_DEBUG 519
#define CONFIG_ATTR_BASIC_MENU 1046
#define CONFIG_ATTR_AUTOPLAY 879
#define CONFIG_ATTR_ALARM_SOUND 1173
#define CONFIG_ATTR_BT_SPK 643
#define CONFIG_ATTR_BT_SINK 746
#define CONFIG_ATTR_BT_SPEAKER 1056
#define CONFIG_ATTR_BT_SOURCE 966
#define CONFIG_ATTR_TTS_SPEED 971
#define CONFIG_ATTR_TTS_PITCH 978
#define CONFIG_ATTR_TTS_VOL 1106
#define CONFIG_ATTR_TELL_TIME 959
#define CONFIG_ATTR_MATRIX_BRIGHTNESS 1837
#define CONFIG_ATTR_HW_VOL_SATELLITE 2044 
#define CONFIG_ATTR_HW_VOL_SUBWOOFER 2065
#define CONFIG_ATTR_HW_VOL_MASTER 1729
#define CONFIG_ATTR_BT_PAIR_WITH 1276
#define CONFIG_ATTR_FFT_BASE_COL 1464
#define CONFIG_ATTR_FFT_MARKER_COL 1695

// end

