#define MATRIX_ANALYSER_MODE_MONO_HOLD 1
#define MATRIX_ANALYSER_MODE_STEREO_HOLD 1
#define MATRIX_ANALYSER_COLOR_01 1
#define MATRIX_ANALYSER_ON 1
#define MATRIX_ANALYSER_OFF 2

void PL_matrix_display_thread(void);

